source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'capybara'
gem 'page-object'
gem 'data_magic'
gem 'pry'
gem 'site_prism'
gem 'cpf_faker'
gem 'faker'
gem 'httparty'